<?php
return array (
  2 => 
  array (
    'posid' => '2',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页拼片子',
    'maxnum' => '100',
    'extention' => '',
    'listorder' => '4',
    'siteid' => '0',
    'thumb' => '',
  ),
  1 => 
  array (
    'posid' => '1',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页会员推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '3',
    'siteid' => '0',
    'thumb' => '',
  ),
  17 => 
  array (
    'posid' => '17',
    'modelid' => '0',
    'catid' => '0',
    'name' => '左侧影片推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '2',
    'siteid' => '0',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '0',
    'catid' => '0',
    'name' => '左侧拼片推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '0',
    'thumb' => '',
  ),
  5 => 
  array (
    'posid' => '5',
    'modelid' => '0',
    'catid' => '0',
    'name' => '推荐下载',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '0',
    'catid' => '0',
    'name' => '图片频道首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '0',
    'catid' => '0',
    'name' => '网站顶部推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  13 => 
  array (
    'posid' => '13',
    'modelid' => '0',
    'catid' => '0',
    'name' => '栏目页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页图片推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  14 => 
  array (
    'posid' => '14',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页头条推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '0',
    'catid' => '0',
    'name' => '栏目首页推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>