<?php
return array (
  1 => 
  array (
    'siteid' => '1',
    'name' => '拼拼影视',
    'dirname' => '',
    'domain' => '/',
    'pc_logo' => '/uploadfile/2017/1127/20171127020832361.png',
    'pc_logo2' => '/statics/images/logo2.jpg',
    'pc_logo3' => '',
    'pc_bannerwidth' => '1920',
    'pc_bannerheight' => '500',
    'pc_company' => '',
    'pc_webmaster' => '',
    'pc_phone' => '',
    'pc_mobile' => '',
    'pc_fax' => '',
    'pc_email' => '',
    'pc_qq' => '',
    'pc_qqlist' => '',
    'pc_weixinqrcode' => '',
    'pc_wapqrcode' => '/uploadfile/2017/1127/20171127020832361.png',
    'pc_welcome' => '您好，欢迎访问公司官网，我们将竭诚为您服务！',
    'pc_announce' => '',
    'pc_remark' => '',
    'pc_topcode' => '',
    'pc_bottomcode' => '',
    'pc_pagenews' => '10',
    'pc_pageproduct' => '12',
    'pc_pagepicture' => '12',
    'pc_pagedownload' => '10',
    'pc_pagevideo' => '12',
    'pc_indexlinkcount' => '35',
    'pc_ipcount' => '0',
    'pc_views' => '1',
    'site_title' => '拼拼影视-大家一起拼电影',
    'keywords' => '拼拼影视-大家一起拼电影',
    'description' => '拼拼影视-大家一起拼电影',
    'release_point' => '',
    'default_style' => 'default',
    'template' => 'default',
    'setting' => '{"upload_maxsize":"2048","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|iso|swf|flv|mp4|ipa|apk|wps","watermark_enable":"0","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/\\/mark.png","watermark_pct":"85","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '8e4c8179-6b9a-11e7-8638-f832e48a4602',
    'url' => '/',
  ),
);
?>